name: Feature Request
description: Suggest a new idea or improvement
title: "[Feature] "
labels: [enhancement]
body:
    - type: textarea
      id: proposal
      attributes:
          label: What would you like to see?
          description: Describe the feature or improvement you're suggesting.
          placeholder: A way to customize animation speed...
      validations:
          required: true

    - type: textarea
      id: motivation
      attributes:
          label: Why is this useful?
          description: Tell us how this feature would help you or other users.
      validations:
          required: false

    - type: checkboxes
      id: contribution
      attributes:
          label: Are you willing to contribute?
          options:
              - label: I'd be happy to open a PR myself!
